baseurl      = "https://abbyad.com/"
title        = "Marc Abbyad"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License." # This message is only used by the RSS template.

googleAnalytics = "368464016"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  backgroundImage = ""
  enableThemeToggle = true

  customCSS = ["css/style.css"]
  customJS  = []

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Marc Abbyad's homepage"
  keywords = "homepage, blog"
  images = [""]

  [params.portrait]
    path = "marc-abbyad.jpg"
    alt = "Marc's headshot"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/MarcAbbyad"

  [[params.social]]
    name = "github"
    url = "https://github.com/abbyad"

  [[params.social]]
    name = "linkedin"
    url = "http://ca.linkedin.com/in/abbyad"

  [[params.social]]
    name = "facebook"
    url = "https://www.facebook.com/abbyad/"

  [params.footer]
    trademark = true
    copyright = true
    author = false
    rss = true
  
    topText = []
    bottomText = []

  # Colors for favicons
  #
  [params.favicon.color]
    mask = "#1b1c1d"
    msapplication = "#1b1c1d"
    theme = "#1b1c1d"

  [params.logo]
#    path = "logo.png"
#    alt = "Marc's logo"
    logoMark     = "<"
    logoText     = "abbyad"
    logoHomeLink = "/"

    # Set true to remove the logo cursor entirely.
    logoCursorDisabled = true

    # Set to a valid CSS color to change the cursor in the logo.
    logoCursorColor    = "#67a2c9"

    # Set to a valid CSS time value to change the animation duration, "0s" to disable.
    logoCursorAnimate  = "0s"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Marc Abbyad"
    subtitle = "Welcome!"
    homeSubtitle = """
**Hello there, nice to meet you!**\n
I lead the Product team at [Medic](https://medic.org) where we design, build, and maintain the [Community Health Toolkit](https://communityhealthtoolkit.org) — an open source software framework for people improving health in the hardest-to-reach communities.\n\n\n
Please reach out if you'd like to connect!
    """

    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>'
    readOtherPosts = "Read other posts"

  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about"

  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact"
